 const placeGoa = document.getElementById('GOA');
 const placeAgra = document.getElementById('AGRA');
 const placeDelhi =document.getElementById('DELHI');
 const placeMUMBAI = document.getElementById('MUMBAI');
 const placeKERALA = document.getElementById('KERALA');
 const PalaceKAR =document.getElementById('KARNATAKA');
 const placeAND = document.getElementById('ANDRAPRADHESH');
 const placeKASHMIR = document.getElementById('KASHMIR');
 const placeBHUTAN =document.getElementById('BHUTAN');
 const placeJAIPUR = document.getElementById('JAIPUR');
 const placeNEPAL = document.getElementById('NEPAL');
 const placePUNJAB =document.getElementById('PUNJAB');
 const placeLadak = document.getElementById('LADAKH');
 const placeOdisha = document.getElementById('ODISHA');
 const placeBANGLADESH =document.getElementById('BANGLADESH');
 const ButtonPlaceGoa = document.getElementById('GoaDetails');
 const ButtonPlaceAgra = document.getElementById('AgraDetails');
 const ButtonPlaceDelhi =document.getElementById('DelhiDetail');
 const ButtonPlaceMUMBAI = document.getElementById('MumbaiDetails');
 const ButtonPlaceKERALA = document.getElementById('KeralaDetails');
 const ButtonPalaceKAR =document.getElementById('KarDetails');
 const ButtonPlaceAND = document.getElementById('TeluguDetails');
 const ButtonPlaceKASHMIR = document.getElementById('KashmirDetails');
 const ButtonPlaceBHUTAN =document.getElementById('ButDetails');
 const ButtonPlaceJAIPUR = document.getElementById('JaipurDetails');
 const ButtonPlaceNEPAL = document.getElementById('NepalDetails');
 const ButtonPlacePUNJAB =document.getElementById('PunjabDetails');
 const ButtonPlaceLadak = document.getElementById('LadDetails');
 const ButtonPlaceOdisha = document.getElementById('OdiDetails');
 const ButtonPlaceBANGLADESH =document.getElementById('BangDetails');
 const PlaceCards =document.getElementById('PlaceCards');
  const ButtonPayGoa = document.getElementById('GoaPay');
 const ButtonpayAgra = document.getElementById('AgraPay');
 const ButtonpayDelhi =document.getElementById('DelhiPay');
 const ButtonpayMUMBAI = document.getElementById('MumbaiPay');
 const ButtonpayKERALA = document.getElementById('KeralaPay');
 const ButtonpayKAR =document.getElementById('KarPay');
 const ButtonpayAND = document.getElementById('AndPay');
 const ButtonpayKASHMIR = document.getElementById('KasPay');
 const ButtonpayBHUTAN =document.getElementById('ButPay');
 const ButtonpayJAIPUR = document.getElementById('JaiPay');
 const ButtonpayNEPAL = document.getElementById('NepPay');
 const ButtonpayPUNJAB =document.getElementById('PunjabPay');
 const ButtonpayLadak = document.getElementById('LadPay');
 const ButtonpayOdisha = document.getElementById('OdiPay');
 const ButtonpayBANGLADESH =document.getElementById('BangPay');
 const Payment = document.getElementById('payment');
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';

ButtonPlaceGoa.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'block';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
});
ButtonPlaceAgra.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'block';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
});
ButtonPlaceDelhi.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'block';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
});
ButtonPlaceMUMBAI.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'block';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
});
ButtonPlaceKERALA.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'block';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
});
ButtonPalaceKAR.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'block';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
});
ButtonPlaceAND.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'block';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
});
ButtonPlaceKASHMIR.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'block';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
});
ButtonPlaceBHUTAN.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'block';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
});
ButtonPlaceJAIPUR.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'block';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
});
ButtonPlaceNEPAL.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'block';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
});
ButtonPlacePUNJAB.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'block';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
});
ButtonPlaceLadak.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='block';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
});
ButtonPlaceOdisha.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='block';
    placeBANGLADESH.style.display='none';
});
ButtonPlaceBANGLADESH.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='block';
});
 ButtonPayGoa.addEventListener('click',function(){
   PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
    Payment.style.display='block';
});
ButtonpayAgra.addEventListener('click',function(){
   PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
    Payment.style.display='block';
});
ButtonpayDelhi.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
    Payment.style.display='block';
});
ButtonpayMUMBAI.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
    Payment.style.display='block';
});
ButtonpayKERALA.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
    Payment.style.display='block';
});
ButtonpayKAR.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
    Payment.style.display='block';
});
ButtonpayAND.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
    Payment.style.display='block';
});
ButtonpayKASHMIR.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
    Payment.style.display='block';
});
ButtonpayBHUTAN.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
    Payment.style.display='block';
});
ButtonpayJAIPUR.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
    Payment.style.display='block';
});
ButtonpayNEPAL.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
    Payment.style.display='block';
});
ButtonpayPUNJAB.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
    Payment.style.display='block';
});
ButtonpayLadak.addEventListener('click',function(){
    PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
    Payment.style.display='block';
});
ButtonpayOdisha.addEventListener('click',function(){
   PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
    Payment.style.display='block';
});
ButtonpayBANGLADESH.addEventListener('click',function(){
   PlaceCards.style.display='none';
    placeGoa.style.display = 'none';
    placeAgra.style.display = 'none';
    placeDelhi.style.display = 'none';
    placeMUMBAI.style.display = 'none';
    placeKERALA.style.display = 'none';
    PalaceKAR.style.display = 'none';
    placeJAIPUR.style.display = 'none';
    placeNEPAL.style.display = 'none';
    placePUNJAB.style.display = 'none';
    placeBHUTAN.style.display = 'none';
    placeKASHMIR.style.display = 'none';
    placeAND.style.display = 'none';
    placeLadak.style.display='none';
    placeOdisha.style.display='none';
    placeBANGLADESH.style.display='none';
    Payment.style.display='block';
});


